-- Supabase Table Schema
CREATE TABLE listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT UNIQUE NOT NULL,
    zone TEXT,
    address TEXT,
    price TEXT,
    details TEXT,
    img TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
