name: Yad2 Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "35 5-17 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: yad2-scraper
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          TG_API: ${{ secrets.TG_API }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python scraper.py

      - name: Commit updated listings.json
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add listings.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update listings $(date -u)"
            git push
          else
            echo "No changes to listings.json"
          fi
